/**
 * The entry module `foldcase lab` scaffolds, as text.
 *
 * ADR-0004: the lab is a library, not a server. The verb writes this module and
 * stops — the consumer's own dev server, the one a Foldkit application already
 * needs, is what builds and serves it. So the whole of this file is string
 * building over paths it was handed: it opens no file, resolves no module and
 * knows nothing of what a catalog file is called.
 */

const SEPARATOR = /[/\\]/

const segmentsOf = (path: string): ReadonlyArray<string> =>
  path.split(SEPARATOR).filter((segment) => segment !== "")

/**
 * The specifier the generated module imports `target` by, relative to the
 * directory `from` sits in. The extension goes, because a bundler resolves the
 * source file itself and TypeScript refuses an explicit `.ts` in an import
 * without a flag most consumers have not set.
 */
const specifierOf = (from: string, target: string): string => {
  const directory = segmentsOf(from).slice(0, -1)
  const to = segmentsOf(target)
  let shared = 0
  while (shared < directory.length && directory[shared] === to[shared]) {
    shared += 1
  }
  const up = directory.length - shared
  const descent = to.slice(shared).join("/").replace(/\.ts$/, "")
  return up === 0 ? `./${descent}` : `${"../".repeat(up)}${descent}`
}

/**
 * The header the generated module opens with. It says what wrote the file and
 * where the decision behind it is written down, so a reader who meets the file
 * before the tool knows both.
 */
const HEADER = `// Generated by \`foldcase lab\`. Regenerate it rather than edit it.
//
// The lab is a library, not a server (ADR-0004). This module is the entry your
// own dev server builds: it imports every catalog found under the target, hands
// them to the lab as the loader's output, and starts the runtime. Point a page
// at it and run the dev server your Foldkit application already needs.

import type { CatalogLoad } from "foldcase/cli"
import { makeLabApplication } from "foldcase/lab"
import { Runtime } from "foldkit"
`

/**
 * The tail: the loader's output assembled from the imports above, and the
 * runtime started on it.
 *
 * `failures` is empty by construction. A file that would not load under Node or
 * Bun is still an ordinary module to a bundler, so the entry names every file
 * that was discovered and lets the dev server resolve them — the verb reports
 * what would not load on its own stderr, where a build error cannot hide it.
 */
const TAIL = `
const load: CatalogLoad = {
  loaded,
  showcases: loaded.map((entry) => entry.showcase),
  failures: [],
}

Runtime.run(
  makeLabApplication({
    load,
    // The element the lab draws into. Rename it to whatever your page carries.
    container: document.getElementById("root"),
  }),
)
`

/**
 * Render the entry module for `files`, as it will be written to `outFile`.
 *
 * Pure: the caller resolves the paths and writes the text. Every catalog is
 * imported statically, so the consumer's bundler sees an ordinary module graph
 * and no path is assembled at runtime. The output is a function of its
 * arguments alone, which is what lets `--check` compare instead of write.
 */
export const labEntryModule = (outFile: string, files: ReadonlyArray<string>): string => {
  const imports = files.map(
    (file, index) =>
      `import { showcases as catalog${index} } from ${JSON.stringify(specifierOf(outFile, file))}\n`,
  )
  // The file each record was read from, carried beside it exactly as the one
  // loader carries it, so the lab's details panel can name it.
  const records = files.map(
    (file, index) =>
      `  ...catalog${index}.map((showcase) => ({ file: ${JSON.stringify(file)}, showcase })),\n`,
  )
  return `${HEADER}\n${imports.join("")}\nconst loaded = [\n${records.join("")}]\n${TAIL}`
}
